### User Service - Change Password
### Requires Authorization Bearer token

@baseUrl = http://localhost:8081
@apiVersion = /api/v1
@contentType = application/json
@accessToken = {{accessToken}}

PUT {{baseUrl}}{{apiVersion}}/users/me/password
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "currentPassword": "SecureAdminPass2024!",
  "newPassword": "SecureAdminPass2025!",
  "confirmPassword": "SecureAdminPass2025!"
}

> {% client.assert(response.status === 200, "Change password failed"); %}